#!/bin/bash
# =============================================================================
# OpenSchool Platform — One-time server provisioning
# Run this ONCE on a fresh VPS to set up everything for production.
#
# Usage:
#   ssh root@your-vps 'bash -s' < scripts/provision.sh
#   # or on the server directly:
#   sudo ./scripts/provision.sh
#
# What it does:
#   1. Creates backup directory
#   2. Installs cron jobs + log rotation
#   3. Creates maintenance config (if not exists)
#   4. Ensures correct permissions
#   5. Verifies the setup
# =============================================================================
set -euo pipefail

# --- Configuration -----------------------------------------------------------
PROJECT_DIR="${PROJECT_DIR:-/opt/openschool}"
BACKUP_DIR="${BACKUP_DIR:-/opt/openschool/backups}"
CONF_FILE="/etc/openschool-maintenance.conf"

# --- Sanity checks ------------------------------------------------------------
if [ "$(id -u)" -ne 0 ]; then
    echo "ERROR: This script must be run as root (sudo)."
    exit 1
fi

if [ ! -d "$PROJECT_DIR" ]; then
    echo "ERROR: Project directory not found: $PROJECT_DIR"
    echo "Clone the repo first: git clone <repo-url> $PROJECT_DIR"
    exit 1
fi

if ! command -v docker &>/dev/null; then
    echo "ERROR: Docker is not installed."
    exit 1
fi

echo "=== OpenSchool Platform — Server Provisioning ==="
echo "Project: $PROJECT_DIR"
echo ""

# --- 1. Backup directory ------------------------------------------------------
echo "[1/5] Creating backup directory..."
mkdir -p "$BACKUP_DIR"
# Set ownership to the user who owns the project
PROJECT_USER=$(stat -c '%U' "$PROJECT_DIR")
chown "$PROJECT_USER":"$PROJECT_USER" "$BACKUP_DIR"
echo "  → $BACKUP_DIR (owner: $PROJECT_USER)"

# --- 2. Cron jobs + log rotation ----------------------------------------------
echo "[2/5] Installing cron jobs..."
"$PROJECT_DIR/scripts/setup-cron.sh"

# --- 3. Maintenance config ----------------------------------------------------
echo "[3/5] Checking maintenance config..."
if [ ! -f "$CONF_FILE" ]; then
    cat > "$CONF_FILE" << 'EOF'
# =============================================================================
# OpenSchool Platform — Maintenance Configuration
# Generated by provision.sh — edit as needed
# =============================================================================

# Backup (default: /opt/openschool/backups, 30 day retention)
# BACKUP_DIR=/opt/openschool/backups
# BACKUP_RETENTION_DAYS=30

# SSL monitoring (set your domain to enable)
# SSL_DOMAIN=yourdomain.com
# SSL_WARNING_DAYS=30

# Discord webhook (paste your webhook URL to enable alerts)
# DISCORD_WEBHOOK_URL=https://discord.com/api/webhooks/...

# Email alerts (requires mailutils)
# NOTIFY_EMAIL=admin@yourdomain.com
EOF
    chmod 644 "$CONF_FILE"
    echo "  → Created $CONF_FILE (edit to configure Discord, SSL, etc.)"
else
    echo "  → $CONF_FILE already exists, skipping"
fi

# --- 4. Permissions -----------------------------------------------------------
echo "[4/5] Setting permissions..."
chmod +x "$PROJECT_DIR/scripts/maintenance.sh"
chmod +x "$PROJECT_DIR/scripts/setup-cron.sh"
chmod +x "$PROJECT_DIR/scripts/provision.sh"
if [ -f "$PROJECT_DIR/.env.prod" ]; then
    chmod 600 "$PROJECT_DIR/.env.prod"
    echo "  → .env.prod secured (600)"
fi
echo "  → Scripts set to executable"

# --- 5. Verify ----------------------------------------------------------------
echo "[5/5] Verifying setup..."

ERRORS=0

if [ -f /etc/cron.d/openschool-maintenance ]; then
    echo "  ✓ Cron jobs installed"
else
    echo "  ✗ Cron jobs NOT installed"
    ERRORS=$((ERRORS + 1))
fi

if [ -f /etc/logrotate.d/openschool-maintenance ]; then
    echo "  ✓ Log rotation configured"
else
    echo "  ✗ Log rotation NOT configured"
    ERRORS=$((ERRORS + 1))
fi

if [ -d "$BACKUP_DIR" ]; then
    echo "  ✓ Backup directory exists"
else
    echo "  ✗ Backup directory missing"
    ERRORS=$((ERRORS + 1))
fi

if [ -f "$CONF_FILE" ]; then
    echo "  ✓ Maintenance config exists"
else
    echo "  ✗ Maintenance config missing"
    ERRORS=$((ERRORS + 1))
fi

echo ""
if [ "$ERRORS" -eq 0 ]; then
    echo "=== Provisioning complete! ==="
    echo ""
    echo "Next steps:"
    echo "  1. Edit $CONF_FILE to set DISCORD_WEBHOOK_URL, SSL_DOMAIN, etc."
    echo "  2. Ensure .env.prod exists with database credentials"
    echo "  3. Test: $PROJECT_DIR/scripts/maintenance.sh health"
    echo ""
else
    echo "=== Provisioning finished with $ERRORS error(s) ==="
    exit 1
fi
